import { z } from "zod";
import type { ContinuationEnvelopeV1, JsonValue } from "../../domain/index.js";
import { ProtocolAdapterError } from "../protocol-error.js";

const ContinuationPayloadSchema = z
  .object({
    kind: z.enum(["input", "authorization"]).default("input"),
    message: z.string().min(1),
  })
  .passthrough();

const OpaqueProtocolIdSchema = z
  .string()
  .min(1)
  .refine((value) => value.trim().length > 0 && value === value.trim(), {
    message: "Protocol IDs must be non-empty and must not contain edge whitespace",
  });

const A2AServerTaskBindingSchema = z
  .object({
    contextId: OpaqueProtocolIdSchema,
    taskId: OpaqueProtocolIdSchema,
  })
  .strict();

export interface A2AServerTaskBinding {
  /** Context owned by the A2A server and bound to this continuation. */
  readonly contextId: string;
  /** Existing task ID generated by the A2A server. */
  readonly taskId: string;
}

export interface A2ASendMessageResponse {
  readonly task: {
    readonly id: string;
    readonly contextId: string;
    readonly status: {
      readonly state: "TASK_STATE_INPUT_REQUIRED" | "TASK_STATE_AUTH_REQUIRED";
      readonly message: {
        readonly role: "ROLE_AGENT";
        readonly messageId: string;
        readonly contextId: string;
        readonly taskId: string;
        readonly parts: readonly [{ readonly text: string }];
      };
      readonly timestamp: string;
    };
    readonly metadata: {
      readonly pausemesh: {
        readonly continuationId: string;
        readonly expiresAt: string;
        readonly schemaVersion: 1;
      };
    };
  };
}

export interface A2ASendMessageRequest {
  readonly message: {
    readonly taskId: string;
    readonly contextId: string;
    readonly role: "ROLE_USER";
    readonly messageId: string;
    readonly parts: readonly [{ readonly data: JsonValue }];
    readonly metadata: {
      readonly pausemesh: {
        readonly continuationId: string;
        readonly schemaVersion: 1;
      };
    };
  };
}

export type A2AAuthorizationControlAction = "reject" | "retry";

function requirePending(continuation: ContinuationEnvelopeV1): void {
  if (continuation.status !== "pending") {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_TRANSITION",
      `Cannot use a ${continuation.status} continuation for an A2A interruption`,
    );
  }
  if (
    !OpaqueProtocolIdSchema.safeParse(continuation.continuationId).success ||
    !z.iso.datetime({ offset: true }).safeParse(continuation.createdAt).success ||
    !z.iso.datetime({ offset: true }).safeParse(continuation.expiresAt).success
  ) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_MESSAGE",
      "Continuation identifiers or timestamps cannot be projected to A2A",
    );
  }
}

function requireBinding(
  continuation: ContinuationEnvelopeV1,
  rawBinding: A2AServerTaskBinding,
): A2AServerTaskBinding {
  const parsed = A2AServerTaskBindingSchema.safeParse(rawBinding);
  if (!parsed.success) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_BINDING",
      "A2A task binding is not protocol-valid",
    );
  }
  const binding = parsed.data;
  if (binding.contextId !== continuation.correlationId) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_BINDING",
      "A2A task binding context does not match the continuation correlation ID",
    );
  }
  return binding;
}

export function toA2AInterruptedTask(
  continuation: ContinuationEnvelopeV1,
  rawBinding: A2AServerTaskBinding,
): A2ASendMessageResponse {
  requirePending(continuation);
  const parsedPayload = ContinuationPayloadSchema.safeParse(continuation.payload);
  if (!parsedPayload.success) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_MESSAGE",
      "Continuation payload cannot be projected as an A2A task status",
    );
  }
  const payload = parsedPayload.data;
  const binding = requireBinding(continuation, rawBinding);

  return {
    task: {
      id: binding.taskId,
      contextId: binding.contextId,
      status: {
        state:
          payload.kind === "authorization"
            ? "TASK_STATE_AUTH_REQUIRED"
            : "TASK_STATE_INPUT_REQUIRED",
        message: {
          role: "ROLE_AGENT",
          messageId: continuation.continuationId,
          contextId: binding.contextId,
          taskId: binding.taskId,
          parts: [{ text: payload.message }],
        },
        timestamp: continuation.createdAt,
      },
      metadata: {
        pausemesh: {
          continuationId: continuation.continuationId,
          expiresAt: continuation.expiresAt,
          schemaVersion: 1,
        },
      },
    },
  };
}

/**
 * Projects non-sensitive input back to an existing A2A task. Authorization credentials are
 * deliberately excluded: A2A 1.0 requires out-of-band delivery unless an extension was negotiated.
 */
export function toA2AInputMessage(
  continuation: ContinuationEnvelopeV1,
  rawBinding: A2AServerTaskBinding,
  response: JsonValue,
  rawMessageId: string,
): A2ASendMessageRequest {
  requirePending(continuation);
  const parsedPayload = ContinuationPayloadSchema.safeParse(continuation.payload);
  if (!parsedPayload.success) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_MESSAGE",
      "Continuation payload cannot be projected as an A2A message",
    );
  }
  const payload = parsedPayload.data;
  if (payload.kind === "authorization") {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_TRANSITION",
      "A2A authorization credentials must be delivered out of band",
    );
  }
  const binding = requireBinding(continuation, rawBinding);
  const parsedMessageId = OpaqueProtocolIdSchema.safeParse(rawMessageId);
  const parsedResponse = z.json().safeParse(response);
  if (!parsedMessageId.success || !parsedResponse.success) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_MESSAGE",
      "A2A input message is not protocol-valid",
    );
  }
  const messageId = parsedMessageId.data;

  return {
    message: {
      taskId: binding.taskId,
      contextId: binding.contextId,
      role: "ROLE_USER",
      messageId,
      parts: [{ data: parsedResponse.data }],
      metadata: {
        pausemesh: {
          continuationId: continuation.continuationId,
          schemaVersion: 1,
        },
      },
    },
  };
}

/**
 * Projects a deliberately narrow, non-sensitive control response for an authorization-required
 * task. Credential material remains out of band; broader negotiation belongs in a negotiated A2A
 * extension owned by the host.
 */
export function toA2AAuthorizationControlMessage(
  continuation: ContinuationEnvelopeV1,
  rawBinding: A2AServerTaskBinding,
  action: A2AAuthorizationControlAction,
  rawMessageId: string,
): A2ASendMessageRequest {
  requirePending(continuation);
  const parsedPayload = ContinuationPayloadSchema.safeParse(continuation.payload);
  if (!parsedPayload.success || parsedPayload.data.kind !== "authorization") {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_TRANSITION",
      "A2A authorization control requires an authorization continuation",
    );
  }
  const parsedAction = z.enum(["reject", "retry"]).safeParse(action);
  const parsedMessageId = OpaqueProtocolIdSchema.safeParse(rawMessageId);
  if (!parsedAction.success || !parsedMessageId.success) {
    throw new ProtocolAdapterError(
      "INVALID_PROTOCOL_MESSAGE",
      "A2A authorization control message is not protocol-valid",
    );
  }
  const binding = requireBinding(continuation, rawBinding);
  return {
    message: {
      taskId: binding.taskId,
      contextId: binding.contextId,
      role: "ROLE_USER",
      messageId: parsedMessageId.data,
      parts: [{ data: { action: parsedAction.data } }],
      metadata: {
        pausemesh: {
          continuationId: continuation.continuationId,
          schemaVersion: 1,
        },
      },
    },
  };
}
